// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.network.http.http3.enable_0rtt", false);
user_pref("app.normandy.startupRolloutPrefs.network.http.http3.enabled", true);
user_pref("app.normandy.user_id", "de9ffd6c-cb97-4c8e-9a21-05deb542d696");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1625859032);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1625859166);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1625859272);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1625859152);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1625859062);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1625859002);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.impressionId", "{942ccfc9-0d2f-4711-b6d9-fcb74acf33b5}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1625859005);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1625859059621");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1625860849621");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1625859020305");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1625880620305");
user_pref("browser.search.region", "AZ");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1625859004");
user_pref("browser.startup.homepage_override.buildID", "20210622155641");
user_pref("browser.startup.homepage_override.mstone", "89.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1625859003);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "89.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "975dc3071ea74f2eaf465ce65561c5b5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210622155641");
user_pref("extensions.lastAppVersion", "89.0.2");
user_pref("extensions.lastPlatformVersion", "89.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"5cd031f9-9606-455a-b30f-36a5142b6628\",\"formautofill@mozilla.org\":\"4c885d0a-e5d7-4996-b91f-f242b982b0b7\",\"pictureinpicture@mozilla.org\":\"b201078b-92d3-4365-85b8-de2d67c03a18\",\"screenshots@mozilla.org\":\"c4ad0598-80da-46a7-baf8-b7facb22ab3c\",\"webcompat-reporter@mozilla.org\":\"b53f546c-d9ca-4a57-8360-1664d654b99c\",\"webcompat@mozilla.org\":\"e937233a-b719-4e59-add0-1cf1080cfa12\",\"default-theme@mozilla.org\":\"5f69cb1a-4f99-474d-b1b4-8720ddfc05d6\",\"google@search.mozilla.org\":\"108aef32-be8f-4380-a3ee-9255a91cf855\",\"amazondotcom@search.mozilla.org\":\"a3c3d170-3ecf-403c-9336-1fa5342c5749\",\"wikipedia@search.mozilla.org\":\"adb85042-1792-42fa-acd5-306fa1a3a77b\",\"bing@search.mozilla.org\":\"ce4798fe-5ee2-4e41-98ae-ae026273ad11\",\"ddg@search.mozilla.org\":\"14101221-5ae4-41f8-9492-fc2cac3e69a6\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1625859020);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1625859256);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20210622155641");
user_pref("media.gmp-manager.lastCheck", 1625859155);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "91b975ad-568d-455e-8229-96b07949a454");
user_pref("toolkit.startup.last_success", 1625859001);
user_pref("toolkit.telemetry.cachedClientID", "e8653cc8-0cea-4ef4-87d9-a35bc1e7c43e");
user_pref("toolkit.telemetry.previousBuildID", "20210622155641");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
