// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.11.0");
user_pref("extensions.lastPlatformVersion", "78.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"e0d99d4b-5ed0-4f68-a518-533b9ea3d771\",\"default-theme@mozilla.org\":\"dd577f0d-848f-4d03-a6ea-105cef511001\"}");
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "6b54f345-df2b-48c1-8e13-d46d067a71a");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("security.sandbox.plugin.tempDirSuffix", "30689466-df4d-4ec1-8a7f-1e1c57e413e0");
user_pref("toolkit.telemetry.cachedClientID", "574f5941-431f-495a-adb1-501cfb4a1e25");
user_pref("toolkit.telemetry.previousBuildID", "20210528153351");
